version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  reviewers:
  - ozzieorca
  ignore:
  - dependency-name: react-redux
    versions:
    - ">= 6.a, < 7"
  - dependency-name: react-redux
    versions:
    - ">= 7.a, < 8"
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
