development:
  bucket: vacumi_dev
  access_key_id: 067B7PVTRAQ34ZTC4MG2
  secret_access_key: bNO9xZIx+e55fnQ4z7G3nM+1TaaBGVQ3aq8U9pW8

test:
  bucket: vacumi_dev
  access_key_id: 067B7PVTRAQ34ZTC4MG2
  secret_access_key: bNO9xZIx+e55fnQ4z7G3nM+1TaaBGVQ3aq8U9pW8

production:
  bucket: vacumi_dev
  access_key_id: 067B7PVTRAQ34ZTC4MG2
  secret_access_key: bNO9xZIx+e55fnQ4z7G3nM+1TaaBGVQ3aq8U9pW8