test:
  from_email: from@example.com
  send_sms: false
  sms_default_keyword: 26am
  site_title: MissionHub
  bitly_host: local.missionhub.com
  bitly_port: 7888
  bitly_username: vincentpaca
  bitly_key: R_1b6fbe0b4987dc3801ddb9f812d60f84
