development:
  adapter: mysql2
  database: missionhub_dev
  username: root
  password: root
  encoding: utf8
  
test:
  adapter: mysql2
  database: missionhub_test
  username: root
  password: root
  encoding: utf8
