development: &dev
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: <%= ENV['DB_ENV_MYSQL_POOL'] || 25 %>
  database: <%= ENV['DB_ENV_MYSQL_DB'] || 'missionhub' %>
  username: <%= ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

production:
  <<: *dev

staging:
  <<: *dev

peoplesoft:
  <<: *dev

simpd:
  <<: *dev
  database: simpd

uscm:
  <<: *dev
  database: prod

test:
  <<: *dev
  pool: <%= ENV['DB_ENV_MYSQL_POOL_TEST'] || 25 %>
  username: <%= ENV['DB_ENV_MYSQL_USER_TEST'] || ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASS_TEST'] || ENV['DB_ENV_MYSQL_PASS'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR_TEST'] || ENV['DB_PORT_3306_TCP_ADDR'] %>
  database: <%= ENV['DB_ENV_MYSQL_DB_TEST'] || 'missionhub_test' %>
