defaults: &defaults
  adapter: mysql2
  username: root
  password:
  encoding: utf8

development:
  database: missionhub_development
  <<: *defaults

test:
  database: missionhub_test
  <<: *defaults

uscm:
  database: missionhub_uscm
  <<: *defaults

production:
  database: missionhub_production
  <<: *defaults