export default {
    communityReport: {
        __typename: 'CommunityReport',
        communityStagesReport: [
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'NOT SURE',
                personalStepsCompletedCount: 12,
                otherStepsCompletedCount: 14,
            },
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'UNINTERESTED',
                personalStepsCompletedCount: 5,
                otherStepsCompletedCount: 12,
            },
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'CURIOUS',
                personalStepsCompletedCount: 4,
                otherStepsCompletedCount: 15,
            },
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'FORGIVEN',
                personalStepsCompletedCount: 8,
                otherStepsCompletedCount: 5,
            },
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'GROWING',
                personalStepsCompletedCount: 2,
                otherStepsCompletedCount: 3,
            },
            {
                __typename: 'CommunityStagesReport',
                pathwayStage: 'GUIDING',
                personalStepsCompletedCount: 6,
                otherStepsCompletedCount: 0,
            },
        ],
        dayReport: [
            {
                __typename: 'DayReport',
                date: '01-01-2019',
                personalStepsCompletedCount: 50,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 43,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 23,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 23,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '02-01-2019',
                personalStepsCompletedCount: 95,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 23,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 53,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 3,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '03-01-2019',
                personalStepsCompletedCount: 42,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 1,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 5,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 2,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 6,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '04-01-2019',
                personalStepsCompletedCount: 53,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 22,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 54,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 5,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '05-01-2019',
                personalStepsCompletedCount: 43,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '06-01-2019',
                personalStepsCompletedCount: 21,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '07-01-2019',
                personalStepsCompletedCount: 30,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '08-01-2019',
                personalStepsCompletedCount: 70,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '09-01-2019',
                personalStepsCompletedCount: 35,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '10-01-2019',
                personalStepsCompletedCount: 60,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 25,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '11-01-2019',
                personalStepsCompletedCount: 50,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '12-01-2019',
                personalStepsCompletedCount: 95,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '13-01-2019',
                personalStepsCompletedCount: 42,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '14-01-2019',
                personalStepsCompletedCount: 53,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '15-01-2019',
                personalStepsCompletedCount: 43,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '16-01-2019',
                personalStepsCompletedCount: 21,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '17-01-2019',
                personalStepsCompletedCount: 30,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '18-01-2019',
                personalStepsCompletedCount: 70,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '19-01-2019',
                personalStepsCompletedCount: 35,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 5,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
            {
                __typename: 'DayReport',
                date: '20-01-2019',
                personalStepsCompletedCount: 60,
                stepsWithOthersStepsCompletedCount: 132,
                communityStagesReport: [
                    {
                        __typename: 'Stage',
                        pathwayStage: 'NOT SURE',
                        personalStepsCompletedCount: 10,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'FORGIVEN',
                        personalStepsCompletedCount: 25,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'UNINTERESTED',
                        personalStepsCompletedCount: 20,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                    {
                        __typename: 'Stage',
                        pathwayStage: 'GROWING',
                        personalStepsCompletedCount: 15,
                        stepsWithOthersStepsCompletedCount: 13,
                    },
                ],
            },
        ],
    },
};
